<?php

/**
 * @file
 * Install file.
 */

use Drupal\user\Entity\Role;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for Tide profile Profile.
 *
 * @see system_install()
 */
function tide_test_install() {
  // Don't do anything else during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  // Set the default and admin theme to Seven. It is important to set themes
  // only to enabled ones (and we are enabling Seven in profile dependencies).
  \Drupal::configFactory()
    ->getEditable('system.theme')
    ->set('default', 'seven')
    ->set('admin', 'seven')
    ->save(TRUE);
}
/**
 * Implements hook_uninstall().
 */
function tide_test_uninstall() {
  // Remove permissions on Test content type to Approver and Editor.
  $roles = ['approver', 'editor'];
  $permissions = [
    'create test content',
    'delete any test content',
    'delete own test content',
    'delete test revisions',
    'edit any test content',
    'edit own test content',
    'revert test revisions',
    'view test revisions',
  ];

  foreach ($roles as $role_name) {
    $role = Role::load($role_name);
    if ($role) {
      foreach ($permissions as $permission) {
        $role->revokePermission($permission);
      }
      $role->save();
    }
  }
}
